plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs48.github.io # the base hostname & protocol for your site
baseurl: /s19  # the subpath of your site, e.g. "/blog"

start_week: 1
start_date: 2019-03-31 00:00:00.00-8:00
num_weeks: 10
extra_exam_week: true
sections: "5pm,&nbsp;6pm,&nbsp;7pm"

cal_dates: >
  [
    {"label":"S19 begins", "date":"2019-04-01" },
    {"label":"Univ Holiday", "date":"2019-05-27" },
    {"label":"S19 instruction ends", "date":"2019-06-07" },
    {"label":"S19 finals start", "date":"2019-06-08" },
    {"label":"S19 finals end", "date":"2019-06-14" },
    {"label":"S19 qtr ends", "date":"2019-06-14" }
  ]


include:
  - _pages
exclude:
  - .sass-cache
  - Gemfile
  - LICENSE
  - .bundle
   - vendor
   
course: "CS48"
qtr: "S19"
qxx: "s19"
quarter: "Spring 2019"

github_url: https://github.com/ucsb-cs48/s19

kramdown:
   parse_block_html: false

timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  project:
    output: true
    permalink: /project/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
  staff:
    output: true
    permalink: /staff/:path



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: project
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  -
    scope:
     path: ""
     type: staff
    values:
     layout: staff

  - scope:
     path: ""
     type: pages
    values:
     layout: default

head_scripts:
   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
